// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/auth/login.post').default>>>>
    }
    '/auth/logout': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/auth/logout').default>>>>
    }
    '/auth/permission-code': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/auth/permission-code').default>>>>
    }
    '/dashboard/data-overview': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/dashboard/data-overview').default>>>>
    }
    '/dashboard/user-analysis-data': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/dashboard/user-analysis-data').default>>>>
    }
    '/': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/index').default>>>>
    }
    '/menu/list': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/menu/list').default>>>>
    }
    '/user/info': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/user/info').default>>>>
    }
  }
}
export {}